# Generated by Django 2.0.7 on 2018-07-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lab',
            options={'ordering': ('course_title', 'lab_number')},
        ),
        migrations.AlterModelOptions(
            name='labtasks',
            options={'ordering': ('lab_id', 'task_number')},
        ),
        migrations.AddField(
            model_name='lab',
            name='lab_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
