# Generated by Django 2.0.7 on 2018-07-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0002_auto_20180726_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtasks',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labtasks',
            name='task_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
