# Generated by Django 2.0.7 on 2018-07-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Labs', '0004_auto_20180730_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtasks',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
